### ISSUE TITLE
Collect introduction content

### ISSUE THREAD

**Issue by Thyra** [Dill-PICL/GOMAP-Paper-2019.1#22]
What does the reader need to know in order to understand our paper? And what would make people interested in what we're talking about?
Collect at least 6 ideas loosely under Introduction here: https://docs.google.com/document/d/1Epaf6g05SIl1PJNHgDMZVEsuECk36xcDPPJu-J17BxQ/edit

- [x] Maybe first something about what functional annotation actually is? - Ha
- [x] The importance of high-quality functional annotation sets. - Ha
- [x] What is a GO? - Ha
- [ ] Reproducibility - Ha
- [ ] Role of rice - Ha
- [ ]  and counting...

**Comment by hhvu0102** [comment]
@Thyra Would you mind looking at the outline I sketched in Ggl Docs?

**Comment by Thyra** [comment]
I like it :-). I also added some more ideas; I think the next step would be to think about what order we could connect them in so that it becomes a compelling story and also start fleshing out some ideas more concretely (collect subitems for why the species are important, why are annotation sets important etc). and then when we have these two things talk it through with Carolyn.
Do you want to take on one of these two tasks?

**Comment by hhvu0102** [comment]
I think the idea #5 you put is greattt.
I can take charge of the importance of annotation sets. About the role of each species, I think each of us can write for our own one?
What I'm wondering now is how to present each species. Should we go into detailed importance of each species in their section instead of in the intro? And in the intro, we can just say 1 or 2 sentences like "Maize, rice, wheat, cotton, soy beans and barley are plants of great importance blah blah"?

**Comment by Thyra** [comment]
Yes I think that may be a good idea, where would you put those sections in the structure?
And then I will think about a good order of the points; if you have the capacity to write more towards any of the other points I'm always grateful for that as well; there is so much to do for this paper and I don't think I can do it all alone.

**Comment by hhvu0102** [comment]
I know it's overwhelming. I'm also in the middle of submitting a poster T___________T But I will definitely spare my time. I will write down the structure I think that would make sense then we can discuss.

**Comment by Thyra** [comment]
Stressful grad student life :-D. OK, yes, that sounds like a good plan. Thank you Ha! :-)

**Comment by hhvu0102** [comment]
I don't know but I feel like I'm "stealing" most of MaizeGAMER paper's introduction...
I created a draft file for the introduction, in which I sketched out the core definitions/ideas with sources. We can modify later.
https://docs.google.com/document/d/1EwWWWLm4pXMqaxaw4RtuF_92eNN2Z2iiillK4yzGuTQ/edit?usp=sharing

**Comment by Thyra** [comment]
Wow, Ha, thank you so much, that gives me a lot of motivation that we have a piece with actual text already :-D
I think it's no problem to start out with MaizeGamer as a template, then we can see what we can leave out or add but generally it is the same topic.

**Comment by Thyra** [comment]
done
